version: '3.1'

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
    ports:
      - 5432:5432
    expose:
      - 5432

  app:
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080