FROM gradle:7.6.1-jdk11-alpine AS build
RUN apk add curl
COPY build.gradle .
COPY src ./src
COPY db ./db
VOLUME //var/run/docker.sock
ENV TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
ENV DOCKER_HOST=tcp://localhost:2375
RUN #ls -l /var/run/docker.sock
RUN #docker ps
RUN #curl --unix-socket /var/run/docker.sock http:/_/_ping
RUN --mount=target="/var/run/docker.sock",src="//var/run/docker.sock",type=bind gradle clean build
#ENTRYPOINT ["gradle", "clean", "build"]
#RUN ls -l ./build/libs
#RUN pwd

#
#FROM openjdk:11.0.15-jdk-slim
#COPY --from=build /home/gradle/build/libs/* file.jar
#ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=docker", "file.jar"]