server.port: 8080
spring.datasource.url: jdbc:postgresql://db:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: example
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto: none
spring.jpa.hibernate.show-sql: true